DecisionTree:
  scratch:
    r:
      max_depth:  5
      min_samples_split: 5
      threshold_sample: 50
      min_gain:  1e-6
    c:
      max_depth:  6
      min_samples_split: 5
      min_samples_leaf: 2
      threshold_sample: 50
  scikit:
    r:
      criterion:  squared_error
      max_depth:  5
      random_state: 0
    c:
      criterion:  entropy
      max_depth:  6
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 0
RandomForest:
  scratch:
    r:
      n_estimators: 100
      random_state: 0
      n_jobs: -1
      random_state: 0
    c:
      n_estimators: 100
      max_depth: 15
      min_samples_split: 8
      min_samples_leaf: 4
      n_jobs: -1
      random_state: 0
  scikit:
    r:
      n_estimators: 100
      criterion: squared_error
      bootstrap: true
      max_features: sqrt
      n_jobs: -1
      random_state: 0

    c:
      n_estimators: 100
      criterion: entropy
      max_depth: 15
      min_samples_split: 8
      min_samples_leaf: 4
      max_features: sqrt
      bootstrap: true
      n_jobs: -1
      random_state: 0
Ridge:
  scratch:
    r:
      alpha: 323.745754281764
  scikit:
    r:
      alpha:  323.745754281764
Lasso:
  scratch:
    r:
      learning_rate:  0.05
      iterations:  5000
      l1_penalty:  0.01
  scikit:
    r:
      alpha:    0.01
      max_iter:  5000
SVM:
  scratch:
    r:
      learning_rate: 1e-2
      C: 500
      epsilon: 0.1
      n_iters: 1000
      random_state: 0
    c:
      learning_rate:  1e-3
      C:    9.0
      n_iters:  100
      shuffle:  true
      random_state:  0
  scikit:
    r:
      C: 5
      epsilon: 0.5
      n_iters: 10000
      max_iter: 10000
      random_state: 0
    c:
      C:    9.0
      loss:    hinge
      fit_intercept:  true
      n_iters:  10000
      max_iter: 10000
      random_state:  0