DecisionTree:
  scratch:
    r:
      max_depth:  5
      min_samples_split: 5
      threshold_sample: 50
      min_gain:  1e-6
    c:
      max_depth:  6
      min_samples_split: 5
      min_samples_leaf: 2
      threshold_sample: 50
  scikit:
    r:
      criterion:  squared_error
      max_depth:  5
      random_state: 0
    c:
      criterion:  entropy
      max_depth:  6
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 0
RandomForest:
  scratch:
    r:
      n_estimators: 50
      max_depth: 10
      min_samples_split: 4
      max_features: Null
      bootstrap: True
      random_state: 0
      n_jobs: -1
    c:
      n_estimators: 200
      max_depth: 7
      min_samples_split: 6
      min_samples_leaf: 4
      max_features: Null
      bootstrap: True
      n_jobs: -1
      random_state: 0
  scikit:
    r:
      n_estimators: 300
      max_depth: 12
      min_samples_split: 4
      min_samples_leaf: 4
      bootstrap: true
      max_features: Null
      n_jobs: -1
      random_state: 0
    c:
      n_estimators: 150
      criterion: gini
      max_depth: 13
      min_samples_split: 8
      min_samples_leaf: 2
      max_features: Null
      bootstrap: true
      n_jobs: -1
      random_state: 0
Ridge:
  scratch:
    r:
      alpha: 10
  scikit:
    r:
      alpha:  10
Lasso:
  scratch:
    r:
      learning_rate:  0.1
      max_iter:  1250
      l1_penalty:  0.1
      tol: 1e-5
  scikit:
    r:
      alpha:    0.01
      max_iter:  5000
SVM:
  scratch:
    r:
      learning_rate: 1e-2
      C: 500
      epsilon: 0.1
      n_iters: 1000
      random_state: 0
    c:
      learning_rate:  1e-3
      C:    9.0
      n_iters:  100
      shuffle:  true
      random_state:  0
  scikit:
    r:
      C: 5
      epsilon: 0.5
      max_iter: 10000
      random_state: 0
    c:
      C:    9.0
      loss:    hinge
      fit_intercept:  true
      max_iter: 10000
      random_state:  0
