DecisionTree:
  scratch:
    r:
      max_depth:  6
      min_samples_split: 5
      threshold_sample: 50
      min_gain:  1e-6
    c:
      max_depth:  6
      min_samples_split: 5
      threshold_sample: 50
  scikit:
    r:
      criterion:  "squared_error"
      max_depth:  5
      random_state:  42
    c:
      criterion:  "entropy"
      max_depth:  6
      random_state:  42
RandomForest:
  scratch:
    r:
    c:
  scikit:
    r:
    c:
Ridge:
  scratch:
    r:
      lambda: 323.745754281764
  scikit:
    r:
Lasso:
  scratch:
    r:
      learning_rate:  0.05
      iterations:  5000
      l1_penalty:  0.01
  scikit:
    r:
      alpha:    0.01
      max_iter:  5000
SVM:
  scratch:
    r:
			learning_rate: 1e-3
			C: 5
			epsilon: 0.5
			n_iters: 2000
			random_state: 0
    c:
      learning_rate:  1e-4
      C:    9.0
      n_iters:  100
      shuffle:  true
      random_state:  0
  scikit:
    r:
			C: 5
			epsilon: 0.5
			n_iters: 2000
			random_state: 0
    c:
      C:    9.0
      loss:    "hinge"
      fit_intercept:  true
      max_iter:  10000
      random_state:  0
